### ISSUE TITLE
Error when try run ./adempiere-access-server 

### ISSUE THREAD

**Issue by e-Evolution** [erpcya/adempiere-gRPC-Server#7]
I try running the last release rt-13.3 adempiere-gRPC-Server and got this error

 ./adempiere-access-server /Users/e-Evolution/AdempierePG.properties
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.spin.base.setup.SetupWrapper` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('WindowDim0=1669|1111 Warehouse=db845ef52e22645b747a0ee020dc2b28 PrintPreview=0607d09432b51724 Warning=Do_not_change_any_of_the_data_as_they_will_have_undocumented_side_effects. AutoNew=d504ada4fe01fe9b ShowAcct=d504ada4fe01fe9b TempDir=76475626baca5fbc5e913d039ee56cdf808138fca47d22b2b0a151c5891c7400d9c485421f35473ad6533682fb09645bc7af0c1d14f3d373 Connection=fc7ff8bcdd51cbd87828c3621d37a2ca73d7185e0b1afabf91f8ae9d22b02f9c3321fe12c7cbadc548ede393500096d3c024dc13b147b2f898a324de1da962b218308018840797dc9152799af6d822b70e438aba1206188fc97294372ddd4c2009c1bd5c9f8fa87e18a3d48922c7fb1d16387d0021baf605b8a02c4e7df0fc21997c48cddd6ec2db1370283bf881ff53f75d33ccf27959423e7ccfaf5deaa939e53672064d07cdb73368361d8e9bc4368f08bafd938a8de3302766dbf8d8cf04407d0fabdb65ce0767d82997d74a14fb5408c662116eaa2ffb46865983aaa1c3 AdempiereSys=d504ada4fe01fe9b CacheWindow=0607d09432b51724 ShowAdvanced=0607d09432b51724 UITheme=0c55dfec0c465c5ceb3bd8ac7cb13235 ShowTrl=0607d09432b51724 SingleInstancePerWindow=d504ada4fe01fe9b Client=4ee7c52423d668d9f2208f9e14749c16 ApplicationUserID=ba30b8f194bf03ad564d171b6ee8e8e3 Organization=da282170804d566f CDate=f633560dc66d46624ac59055b9198cf88b7489a546722bc8 Divider=519 ApplicationPassword=1b7c2dc3600e813a Role=4ee7c52423d668d9909f5c955f0bfff3ca92e61dde7e7e70 AutoCommit=0607d09432b51724 Charset=79cf4e2e0345fd0e TraceFile=d504ada4fe01fe9b DataSource=25149d4b9a47f4def17237ffbe3f8d5e6dc2facaa9e0623c LoadTabMetaDataBackground=d504ada4fe01fe9b LogMigrationScript=d504ada4fe01fe9b WarningD=Einstellungen_nicht_aendern,_da_diese_undokumentierte_Nebenwirkungen_haben. AutoLogin=d504ada4fe01fe9b Printer= TraceLevel=afcc0a34e2901f7f Language=ddb3fce83ab1ccbf5eb5012c7ca3d126 WindowLoc0=3738|268 UILookFeel=0c55dfec0c465c5cb0d8e08f9070a667 OpenWindowMaximized=d504ada4fe01fe9b ValidateConnectionOnStartup=d504ada4fe01fe9b StorePassword=0607d09432b51724')
 at [Source: (File); line: 3, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1451)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3299)
	at org.spin.base.setup.SetupLoader.<init>(SetupLoader.java:48)
	at org.spin.base.setup.SetupLoader.loadSetup(SetupLoader.java:128)
	at org.spin.grpc.util.AccessServer.main(AccessServer.java:104)

**Comment by yamelsenih** [comment]
Hi @e-Evolution please try it with a yml file like is defined in resources.

I will to add it to readme

**Comment by yamelsenih** [comment]
Here are some examples: https://github.com/erpcya/adempiere-gRPC-Server/tree/master/resources

**Comment by e-Evolution** [comment]
Now I review the source code and see that now use yml format, got successful start  :

./adempiere-access-server /Users/e-Evolution/Develop/ADempiere/adempiere-gRPC-Server/resources/access.yml 
[INFO] MLog clients using com.mchange.v2.log.FallbackMLog logging.
[INFO] Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? true; trace: 10]
jun 24, 2020 9:38:00 PM org.spin.grpc.util.AccessServer start
INFORMACIÓN: Server started, listening on 50050

@yamelsenih Thank you

**Comment by yamelsenih** [comment]
https://github.com/erpcya/adempiere-gRPC-Server#runing-server
